### ISSUE TITLE
Proceso de Desarrollo de Software

### ISSUE THREAD

**Issue by vanita88** [vanita88/Proyecto_ISPC#2]

**Comment by vanita88** [comment]
Tu tema es el segundo item. Para que nos vayamos ordenando al escribir, sugiero que pongas el titulo con un (2.) para saber que tu tema irá segundo. De esa forma, le damos un orden a los textos.

**Comment by Morgwens** [comment]
Listo, tarea terminada. Espero que haya quedado bien, aunque todavía no logro hacer el comentario al pie de página.
